spring:
  cloud:
    aws:
      credentials:
        access-key: test-key
        secret-key: test-secret
      region:
        static: sa-east-1
      endpoint: http://localhost:4566
      queue:
        name: "demo"